classes:
  - nsidc_miniconda
  - nsidc_emacs

nsidc_miniconda::install:
  /opt/miniconda:
    python_version: "2"
    build: true
    config:
      channels:
        anaconda_nsidc_dev: true
        extra: []
    packages:
      - flake8
      - flake8-quotes
      - invoke
      - nose
      - nose-exclude
